[package]
name = "tokio-mc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
byteorder = "1.5.0"
bytes = "1.5.0"
thiserror = "1.0.58"
tokio = { version = "1.35.1",  features = ["full"]  }
regex = "1.11.1"